### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by Hero7785** [snowkit/snow#98]
Hello, I have been trying to use the luxe game engine on linux, but I cannot get my game to compile because hxcpp compiles the header file into a precompiled header file.
Here is the error message:
flow / 1.0.0-alpha.2 (node.js v0.12.7)
flow / target is linux ( arch 64 )
flow / haxe version 3.4.0

flow / build - Space-Boats 0.0.1 for linux
flow / build - running haxe ...
flow / build - running hxcpp for arch 64 ...
Creating /home/josh/dev/LSB/bin/linux64.build/cpp/obj/linux64/__pch/haxe/hxcpp.h.gch...
Compiling group: haxe
g++ -Iinclude -I/usr/local/lib/haxelib/linc_ogg/git//lib/ -I/usr/local/lib/haxelib/linc_ogg/git//linc/ -I/usr/local/lib/haxelib/linc_ogg/git//lib//ogg/include/ -I/usr/local/lib/haxelib/linc_ogg/git//lib//vorbis/include/ -I/usr/local/lib/haxelib/linc_ogg/git//lib//theora/include/ -DNATIVE_TOOLKIT_OGG -DNATIVE_TOOLKIT_VORBIS -DNATIVE_TOOLKIT_THEORA -DLINC_OPENAL -I/usr/local/lib/haxelib/linc_openal/git//linc/ -I/usr/local/lib/haxelib/linc_opengl/git//linc/ -I/usr/local/lib/haxelib/linc_opengl/git//lib/glew/include/ -DLINC_OPENGL_GLEW -DGLEW_STATIC -DLINC_SDL -I/usr/local/lib/haxelib/linc_sdl/git//linc/ -I/usr/local/lib/haxelib/linc_sdl/git//lib/sdl/include/ -I/usr/local/lib/haxelib/linc_sdl/git//lib/sdl/include/configs/linux/ -DHAVE_LIBC -DNATIVE_TOOLKIT_SDL -I/usr/local/lib/haxelib/linc_stb/git//lib/ -I/usr/local/lib/haxelib/linc_stb/git//linc/ -I/usr/local/lib/haxelib/linc_timestamp/git//linc/ -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=331(haxe) -m64 -DHXCPP_M64 -I/usr/local/lib/haxelib/hxcpp/3,4,49/include ... tags=[haxe,static]
 - src/snow/types/_Types/InputEventType_Impl_.cpp 
 - src/sys/FileSystem.cpp 
 - src/snow/types/_Types/SystemEventType_Impl_.cpp 
 - src/snow/types/_Types/WindowEventType_Impl_.cpp 
 - src/snow/types/_Types/GamepadDeviceEventType_Impl_.cpp 
 - src/snow/types/_Types/TextEventType_Impl_.cpp 
 - src/snow/types/_Types/GamepadEventType_Impl_.cpp 
 - src/snow/types/_Types/TouchEventType_Impl_.cpp 
 - src/snow/types/_Types/MouseEventType_Impl_.cpp 
 - src/snow/types/_Types/KeyEventType_Impl_.cpp 
 - src/snow/types/ModState.cpp 
 - src/snow/types/InputEvent.cpp 
 - src/snow/types/GamepadEvent.cpp 
 - src/snow/types/TouchEvent.cpp 
 - src/snow/types/MouseEvent.cpp 
 - src/snow/types/TextEvent.cpp 
 - src/snow/types/KeyEvent.cpp 
 - src/snow/types/WindowEvent.cpp 
 - src/snow/types/SystemEvent.cpp 
 - src/snow/types/_Types/OpenGLProfile_Impl_.cpp 
 - src/snow/types/_Types/AudioState_Impl_.cpp 
 - src/snow/types/_Types/AudioEvent_Impl_.cpp 
 - src/snow/types/_Types/AudioFormatType_Impl_.cpp 
 - src/snow/types/ImageData.cpp 
 - src/snow/types/_Types/AssetType_Impl_.cpp 
 - src/snow/types/_Types/ExtensionsInit.cpp 
 - src/snow/types/Error.cpp 
 - src/snow/types/Config.cpp 
 - src/snow/systems/io/IO.cpp 
Error: In file included from include/snow/core/native/io/IO.h:14:0,
                 from ./src/snow/systems/io/IO.cpp:44:
/usr/local/lib/haxelib/linc_sdl/git//linc/linc_sdl.h:3:19: fatal error: /home/josh/dev/LSB/bin/linux64.build/cpp/obj/linux64/__pch/haxe/hxcpp.h: No such file or directory
compilation terminated.
flow / 
 build - stopping because of errors in hxcpp compile, while building arch 64 

Since it generates a .h.gch file, snow cannot use it; is there any way around this.  I am using the most recent versions of both haxe and hxcpp, but I think the problem is with gcc not haxe.  Any help.

**Comment by underscorediscovery** [comment]
Hi, sorry about that, it's a hxcpp issue. 

You can try define `NO_PRECOMPILED_HEADERS` in the project file, in the defines section. Ignore the `luxe` dependency, I just took this from [another thread](https://github.com/underscorediscovery/luxe/issues/417#issuecomment-280361379). 

<img width="542" alt="screen shot 2017-02-16 at 11 55 23 am" src="https://cloud.githubusercontent.com/assets/236374/23027460/d4a9016a-f43e-11e6-878b-898b23462397.png">

**Comment by Hero7785** [comment]
Thank you
